export enum NODE_TYPE {
  MESH = "MESH",
  SCENE = "SCENE",
  CAMERA = "CAMERA",
}

export enum GEOMETRY_TYPE {
  BASE = "BASE_GEOMETRY",
  BOX = "BOX",

  // HOLLOW OBJECT
  HOLLOW_TRIANGULAR_PRISM = "HOLLOW_TRIANGULAR_PRISM",
  HOLLOW_BOX = "HOLLOW_BOX",
  HOLLOW_PENTA_PRISM = "HOLLOW_PENTA_PRISM",
  HOLLOW_HEXAGONAL_PRISM = "HOLLOW_HEXAGONAL_PRISM",
}

export enum MATERIAL_TYPE {
  BASE = "SHADER_MATERIAL",
  BASIC = "BASIC_MATERIAL",
  PHONG = "PHONG_MATERIAL",
}
