export enum NODE_TYPE {
  MESH = "MESH",
  SCENE = "SCENE",
  CAMERA = "CAMERA",
}

export enum GEOMETRY_TYPE {
  BASE = "BASE_GEOMETRY",
  BOX = "BOX",

  // HOLLOW OBJECT
  HOLLOW_BOX = "HOLLOW_BOX",
}

export enum MATERIAL_TYPE {
  BASE = "SHADER_MATERIAL",
  BASIC = "BASIC_MATERIAL",
}
